/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views2;

import Models.Admin;
import Models.Conductor;
import Models.Ruta;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author Mihae
 */
public class AdminViajesCrear extends javax.swing.JFrame {

    /**
     * Creates new form LoginPasajero
     */
    Admin admin;
   
    public AdminViajesCrear(Admin admin) {
        this.admin = admin;
        initComponents();
        resultado_text.setText("");
        combo_box();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fecha_salida_input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hora_salida_input = new javax.swing.JTextField();
        anadir_button = new javax.swing.JButton();
        resultado_text = new javax.swing.JLabel();
        ruta_combobox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        LabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 82, 162));
        jLabel1.setText("Añadir Viaje");

        jLabel2.setText("Fecha salida (aaaa/mm/dd)");

        jLabel3.setText("Ruta");

        jLabel5.setText("Hora de Salida (HH:MM)");

        anadir_button.setBackground(new java.awt.Color(80, 99, 161));
        anadir_button.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        anadir_button.setForeground(new java.awt.Color(255, 255, 255));
        anadir_button.setText("Añadir");
        anadir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadir_buttonActionPerformed(evt);
            }
        });

        resultado_text.setText("Respuesta");

        ruta_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ruta_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta_comboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(anadir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(resultado_text))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel1))
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(fecha_salida_input, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(hora_salida_input)
                            .addComponent(ruta_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha_salida_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(ruta_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hora_salida_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(anadir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultado_text)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(LabelError)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void combo_box(){
        List<Ruta> rutas = admin.ver_rutas();
        
        ruta_combobox.removeAllItems();
        
        if(rutas != null){
            for(Ruta ruta:rutas){
                ruta_combobox.addItem(ruta.get_id_ruta() + ": " + ruta.get_origen() + "->" + ruta.get_destino());
            }
        }
    }
    
    private void anadir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadir_buttonActionPerformed
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate fecha;
        try{
            fecha = LocalDate.parse(fecha_salida_input.getText(), formatter);
        } catch(Exception e){
            System.out.println("Fecha de salida error");
            resultado_text.setText("Ingrese bien el formato");
            return;
        }
        
        LocalTime hora_salida;
        try{
            // Usar un formateador específico para hh:mm
            DateTimeFormatter horaFormatter = DateTimeFormatter.ofPattern("HH:mm");
            hora_salida = LocalTime.parse(hora_salida_input.getText(), horaFormatter);
        } catch (Exception e){
            System.out.println("Hora de salida error");
            resultado_text.setText("Ingrese bien el formato (HH:mm)");
            return;
        }
        
        String id_ruta = ruta_combobox.getSelectedItem().toString().split(":")[0].trim();
        /*
        
        List<Viaje> viajes_activos = admin.ver_viajes_activos();
        List<Ruta> rutas = admin.ver_rutas();
        
        Ruta ruta_elegida = null;
        int menor_repeticion = -1;
        for(Ruta ruta:rutas){
            int aux=0;
            for(Viaje viaje:viajes_activos){
                if(viaje.get_ruta().get_id_ruta().equals(ruta.get_id_ruta())){
                    aux++;
                }
            }
            
            if(menor_repeticion != -1){
                if(aux<menor_repeticion){
                    menor_repeticion = aux;
                    ruta_elegida = ruta;
                }
                continue;
            }
            menor_repeticion = aux;
            ruta_elegida = ruta;
        }
        */
        List<Conductor> conductores = admin.ver_conductores_libres();
        Random random = new Random();
        int indice = random.nextInt(conductores.size());
        
        boolean exito = admin.crear_viaje(fecha, id_ruta, conductores.get(indice).get_dni(), hora_salida);
        
        if(!exito){
            resultado_text.setText("No se pudo crear el viaje");
            return;
        }
        
        resultado_text.setText("Viaje creado!!");
        JOptionPane.showMessageDialog(null, "Creacion exitosa", "Creacion exitosa", JOptionPane.INFORMATION_MESSAGE);
        resultado_text.setText("Creacion exitosa");
        
    }//GEN-LAST:event_anadir_buttonActionPerformed

    private void ruta_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruta_comboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViajesCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViajesCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViajesCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViajesCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminConductorCrear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelError;
    private javax.swing.JButton anadir_button;
    private javax.swing.JTextField fecha_salida_input;
    private javax.swing.JTextField hora_salida_input;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultado_text;
    private javax.swing.JComboBox<String> ruta_combobox;
    // End of variables declaration//GEN-END:variables
}
