package Views2;

import Models.Conductor;
import Repository.ConductorRepository;
import Repository.RegulacionLaboral;
import javax.swing.JOptionPane;
import java.sql.Statement;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Mihae
 */
public class ConductorVehiculoEditar extends javax.swing.JPanel {

    /**
     * Creates new form PerfilAdmin
     */
    
    private Conductor conductor;
    private Statement st;

    public ConductorVehiculoEditar(Conductor conductor, Statement st) {
        this.st = st;
        this.conductor = conductor;
        initComponents();
        nuevo_modelo_label.setVisible(false);
        nuevo_modelo_input.setVisible(false);
        nuevo_modelo_button.setVisible(false);
        
        nuevo_capacidad_label1.setVisible(false);
        nuevo_capacidad_input1.setVisible(false);
        nuevo_capacidad_button1.setVisible(false);
        
        nuevo_placa_label.setVisible(false);
        nuevo_placa_input.setVisible(false);
        nuevo_placa_button.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contra_input = new javax.swing.JPasswordField();
        ingresar_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nuevo_modelo_label = new javax.swing.JLabel();
        nuevo_modelo_button = new javax.swing.JButton();
        nuevo_modelo_message = new javax.swing.JLabel();
        nuevo_nombre_message = new javax.swing.JLabel();
        nuevo_placa_label = new javax.swing.JLabel();
        nuevo_placa_input = new javax.swing.JTextField();
        nuevo_placa_button = new javax.swing.JButton();
        nuevo_placa_message = new javax.swing.JLabel();
        nuevo_provincia_message = new javax.swing.JLabel();
        nuevo_departamento_message = new javax.swing.JLabel();
        nuevo_capacidad_label1 = new javax.swing.JLabel();
        nuevo_capacidad_input1 = new javax.swing.JTextField();
        nuevo_capacidad_button1 = new javax.swing.JButton();
        nuevo_capacidad_message = new javax.swing.JLabel();
        nuevo_modelo_input = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1010, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1010, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 580));

        contra_input.setBackground(new java.awt.Color(240, 245, 247));
        contra_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        contra_input.setMinimumSize(new java.awt.Dimension(370, 22));
        contra_input.setPreferredSize(new java.awt.Dimension(370, 22));

        ingresar_button.setBackground(new java.awt.Color(41, 82, 85));
        ingresar_button.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ingresar_button.setForeground(new java.awt.Color(240, 245, 247));
        ingresar_button.setText("Ingresar");
        ingresar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 20, 20));
        jLabel1.setText("Ingrese su contraseña para modificar sus datos");

        nuevo_modelo_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nuevo_modelo_label.setForeground(new java.awt.Color(20, 20, 20));
        nuevo_modelo_label.setText("Actualizar modelo del vehiculo");

        nuevo_modelo_button.setBackground(new java.awt.Color(41, 82, 85));
        nuevo_modelo_button.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nuevo_modelo_button.setForeground(new java.awt.Color(240, 245, 247));
        nuevo_modelo_button.setText("Modificar");
        nuevo_modelo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_modelo_buttonActionPerformed(evt);
            }
        });

        nuevo_placa_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nuevo_placa_label.setForeground(new java.awt.Color(20, 20, 20));
        nuevo_placa_label.setText("Actualizar placa");

        nuevo_placa_input.setBackground(new java.awt.Color(240, 245, 247));
        nuevo_placa_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nuevo_placa_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_placa_inputActionPerformed(evt);
            }
        });

        nuevo_placa_button.setBackground(new java.awt.Color(41, 82, 85));
        nuevo_placa_button.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nuevo_placa_button.setForeground(new java.awt.Color(240, 245, 247));
        nuevo_placa_button.setText("Modificar");
        nuevo_placa_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_placa_buttonActionPerformed(evt);
            }
        });

        nuevo_capacidad_label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nuevo_capacidad_label1.setForeground(new java.awt.Color(20, 20, 20));
        nuevo_capacidad_label1.setText("Actualizar capacidad del vehiculo");

        nuevo_capacidad_input1.setBackground(new java.awt.Color(240, 245, 247));
        nuevo_capacidad_input1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nuevo_capacidad_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_capacidad_input1ActionPerformed(evt);
            }
        });

        nuevo_capacidad_button1.setBackground(new java.awt.Color(41, 82, 85));
        nuevo_capacidad_button1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nuevo_capacidad_button1.setForeground(new java.awt.Color(240, 245, 247));
        nuevo_capacidad_button1.setText("Modificar");
        nuevo_capacidad_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_capacidad_button1ActionPerformed(evt);
            }
        });

        nuevo_modelo_input.setBackground(new java.awt.Color(240, 245, 247));
        nuevo_modelo_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nuevo_modelo_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_modelo_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ingresar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contra_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevo_capacidad_label1)
                    .addComponent(nuevo_modelo_label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nuevo_modelo_input, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nuevo_modelo_button))
                    .addComponent(nuevo_placa_label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nuevo_placa_input, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nuevo_placa_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nuevo_capacidad_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nuevo_capacidad_button1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevo_capacidad_message)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevo_nombre_message)
                            .addComponent(nuevo_modelo_message)
                            .addComponent(nuevo_placa_message)
                            .addComponent(nuevo_provincia_message)
                            .addComponent(nuevo_departamento_message))))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(nuevo_modelo_message)
                        .addGap(69, 69, 69)
                        .addComponent(nuevo_nombre_message)
                        .addGap(69, 69, 69)
                        .addComponent(nuevo_placa_message)
                        .addGap(69, 69, 69)
                        .addComponent(nuevo_provincia_message)
                        .addGap(69, 69, 69)
                        .addComponent(nuevo_departamento_message))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contra_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingresar_button)
                        .addGap(18, 18, 18)
                        .addComponent(nuevo_modelo_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevo_modelo_button)
                            .addComponent(nuevo_modelo_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(nuevo_placa_label)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevo_placa_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevo_placa_button))
                        .addGap(18, 18, 18)
                        .addComponent(nuevo_capacidad_label1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevo_capacidad_input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevo_capacidad_button1))))
                .addGap(49, 49, 49)
                .addComponent(nuevo_capacidad_message)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevo_capacidad_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_capacidad_button1ActionPerformed
        String capacidadStr = nuevo_capacidad_input1.getText();

    if (capacidadStr.isEmpty()) {
        nuevo_capacidad_message.setText("Ingrese una capacidad válida");
        return;
    }

    try {
        int nuevaCapacidad = Integer.parseInt(capacidadStr);
        // Actualizar capacidad del vehículo
        conductor.set_capacidad_vehiculo(nuevaCapacidad);
        boolean exito = conductor.actualizar_vehiculo(conductor.get_placa_vehiculo(), conductor.get_modelo_vehiculo(), nuevaCapacidad, st);
        
        if (!exito) {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar la capacidad del vehículo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Capacidad del vehículo actualizada exitosamente!!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        nuevo_capacidad_input1.setText(""); // Limpiar el campo de entrada
    } catch (NumberFormatException e) {
        nuevo_capacidad_message.setText("Ingrese un número válido para la capacidad");
    }


    }//GEN-LAST:event_nuevo_capacidad_button1ActionPerformed

    private void nuevo_capacidad_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_capacidad_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo_capacidad_input1ActionPerformed

    private void nuevo_placa_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_placa_buttonActionPerformed
         String nuevaPlaca = nuevo_placa_input.getText();

    if (nuevaPlaca.isEmpty()) {
        nuevo_placa_message.setText("Ingrese una placa válida");
        return;
    }

    // Actualizar placa del vehículo
    conductor.set_placa_vehiculo(nuevaPlaca);
    boolean exito = conductor.actualizar_vehiculo(nuevaPlaca, conductor.get_modelo_vehiculo(), conductor.get_capacidad_vehiculo(), st);
    
    if (!exito) {
        JOptionPane.showMessageDialog(this, "No se pudo actualizar la placa del vehículo", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    JOptionPane.showMessageDialog(this, "Placa del vehículo actualizada exitosamente!!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    nuevo_placa_input.setText(""); // Limpiar el campo de entrada

    }//GEN-LAST:event_nuevo_placa_buttonActionPerformed

    private void nuevo_placa_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_placa_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo_placa_inputActionPerformed

    private void nuevo_modelo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_modelo_buttonActionPerformed
       String nuevoModelo = nuevo_modelo_input.getText();

    if (nuevoModelo.isEmpty()) {
        nuevo_modelo_message.setText("Ingrese un modelo válido");
        return;
}

    // Actualizar modelo del vehículo
    conductor.set_modelo_vehiculo(nuevoModelo);
    boolean exito = conductor.actualizar_vehiculo(conductor.get_placa_vehiculo(), nuevoModelo, conductor.get_capacidad_vehiculo(), st);
    
    if (!exito) {
        JOptionPane.showMessageDialog(this, "No se pudo actualizar el modelo del vehículo", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    JOptionPane.showMessageDialog(this, "Modelo del vehículo actualizado exitosamente!!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    nuevo_modelo_input.setText(""); // Limpiar el campo de entrada

    }//GEN-LAST:event_nuevo_modelo_buttonActionPerformed

    private void ingresar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_buttonActionPerformed
        String contra = new String(contra_input.getPassword());
        if(conductor.get_contrasena().equals(contra)){
            nuevo_modelo_label.setVisible(true);
            nuevo_modelo_input.setVisible(true);
            nuevo_modelo_button.setVisible(true);


            nuevo_capacidad_label1.setVisible(true);
            nuevo_capacidad_input1.setVisible(true);
            nuevo_capacidad_button1.setVisible(true);
            
            nuevo_placa_label.setVisible(true);
            nuevo_placa_input.setVisible(true);
            nuevo_placa_button.setVisible(true);
        } else {
            // Si la contraseña es incorrecta, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta. Vuelva a intentar.", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_ingresar_buttonActionPerformed

    private void nuevo_modelo_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_modelo_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo_modelo_inputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contra_input;
    private javax.swing.JButton ingresar_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nuevo_capacidad_button1;
    private javax.swing.JTextField nuevo_capacidad_input1;
    private javax.swing.JLabel nuevo_capacidad_label1;
    private javax.swing.JLabel nuevo_capacidad_message;
    private javax.swing.JLabel nuevo_departamento_message;
    private javax.swing.JButton nuevo_modelo_button;
    private javax.swing.JTextField nuevo_modelo_input;
    private javax.swing.JLabel nuevo_modelo_label;
    private javax.swing.JLabel nuevo_modelo_message;
    private javax.swing.JLabel nuevo_nombre_message;
    private javax.swing.JButton nuevo_placa_button;
    private javax.swing.JTextField nuevo_placa_input;
    private javax.swing.JLabel nuevo_placa_label;
    private javax.swing.JLabel nuevo_placa_message;
    private javax.swing.JLabel nuevo_provincia_message;
    // End of variables declaration//GEN-END:variables

}