/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views2;

import Models.Boleto;
import Models.Pasajero;
import Models.Viaje;
import Repository.BoletoRepository;
import javax.swing.*;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mihae
 */
public class PasajeroHistorialFecha extends javax.swing.JFrame {

    private Statement st;
    private Pasajero pasajero;
    private JTable tabla_viajes;  
    private JTable datos_conductor;
    private PasajeroHistorial panelHistorial; 

    public PasajeroHistorialFecha(Statement st, Pasajero pasajero, PasajeroHistorial panelHistorial) {
        this.st = st;
        this.pasajero = pasajero;
        this.panelHistorial = panelHistorial;
        
        // Obtener referencias de las tablas del panel principal
        this.tabla_viajes = panelHistorial.tabla_viajes1;  // Usa la tabla con más columnas
        this.datos_conductor = panelHistorial.datos_conductor;
        
        initComponents();
        this.setLocationRelativeTo(null);
        cargarFechas();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    
        private void cargarFechas() {
        // Cargar años
        for (int i = 2020; i <= 2030; i++) {
            año_desde.addItem(String.valueOf(i));
            año_hasta.addItem(String.valueOf(i));
        }

        // Cargar meses
        for (int i = 1; i <= 12; i++) {
            mes_desde.addItem(String.format("%02d", i));
            mes_hasta.addItem(String.format("%02d", i));
        }

        // Cargar días
        for (int i = 1; i <= 31; i++) {
            dia_desde.addItem(String.format("%02d", i));
            dia_hasta.addItem(String.format("%02d", i));
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscar_porfecha = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        año_desde = new javax.swing.JComboBox<>();
        mes_desde = new javax.swing.JComboBox<>();
        dia_desde = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        año_hasta = new javax.swing.JComboBox<>();
        mes_hasta = new javax.swing.JComboBox<>();
        dia_hasta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 245, 247));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(22, 38, 35));
        jLabel1.setText("Buscar Por Fecha");

        buscar_porfecha.setBackground(new java.awt.Color(41, 82, 85));
        buscar_porfecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buscar_porfecha.setForeground(new java.awt.Color(240, 245, 247));
        buscar_porfecha.setText("Buscar");
        buscar_porfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_porfechaActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 82, 85));
        jLabel2.setText("Desde");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 112, -1));

        año_desde.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(año_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, -1, -1));

        mes_desde.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(mes_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 57, -1, -1));

        dia_desde.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(dia_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 57, 50, -1));

        jLabel4.setText("Dia");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel5.setText("Mes");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel3.setText("Año");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(41, 82, 85));
        jLabel6.setText("Hasta");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 112, -1));

        año_hasta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel3.add(año_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, -1, -1));

        mes_hasta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel3.add(mes_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 57, -1, -1));

        dia_hasta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel3.add(dia_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 57, 50, -1));

        jLabel7.setText("Dia");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel8.setText("Mes");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel9.setText("Año");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(buscar_porfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buscar_porfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_porfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_porfechaActionPerformed
        // El código que ya tenías, pero usando this.pasajero en lugar de pasajero
        int añoDesde = Integer.parseInt((String) año_desde.getSelectedItem());
        int mesDesde = Integer.parseInt((String) mes_desde.getSelectedItem());
        int diaDesde = Integer.parseInt((String) dia_desde.getSelectedItem());

        int añoHasta = Integer.parseInt((String) año_hasta.getSelectedItem());
        int mesHasta = Integer.parseInt((String) mes_hasta.getSelectedItem());
        int diaHasta = Integer.parseInt((String) dia_hasta.getSelectedItem());

        // Crear las fechas
        LocalDate fechaDesde = LocalDate.of(añoDesde, mesDesde, diaDesde);
        LocalDate fechaHasta = LocalDate.of(añoHasta, mesHasta, diaHasta);

        // Obtener el historial de viajes
        List<Viaje> viajes = this.pasajero.ver_historial_viajes(st);
        List<Boleto> boletos = new BoletoRepository(st).listar();
    
        // Limpiar las tablas antes de agregar nuevos datos
        DefaultTableModel modeloViaje = (DefaultTableModel) tabla_viajes.getModel();
        DefaultTableModel modeloConductor = (DefaultTableModel) datos_conductor.getModel();
        modeloViaje.setRowCount(0);
        modeloConductor.setRowCount(0);

        // Filtrar y llenar las tablas
        for (Viaje viaje : viajes) {
            LocalDate fechaViaje = viaje.get_fecha_salida(); 

            if ((fechaViaje.isEqual(fechaDesde) || fechaViaje.isAfter(fechaDesde)) &&
                (fechaViaje.isEqual(fechaHasta) || fechaViaje.isBefore(fechaHasta))) {
            
                // Buscar el boleto correspondiente
                String idBoleto = "N/A";
                for (Boleto boleto : boletos) {
                    if (boleto.get_viaje().get_id_viaje().equals(viaje.get_id_viaje()) && 
                        boleto.get_pasajero().get_dni().equals(this.pasajero.get_dni())) {
                        idBoleto = boleto.get_id_boleto();
                        break;
                    }
                }
            
                // Agregar datos a la tabla de viajes
                String estadoTexto = viaje.get_estado() ? "Disponible" : "Terminado";
                modeloViaje.addRow(new Object[]{
                    idBoleto, // ID Boleto
                    viaje.get_id_viaje(),   // ID Viaje
                    viaje.get_fecha_salida(),
                    viaje.get_ruta().get_origen(),
                    viaje.get_ruta().get_destino(),
                    viaje.get_ruta().get_precio(),
                    estadoTexto
                });

                // Agregar datos a la tabla de conductores
                if (viaje.get_conductor() != null) {
                    modeloConductor.addRow(new Object[]{
                        viaje.get_id_viaje(), // ID Viaje
                        viaje.get_conductor().get_nombre() != null && !viaje.get_conductor().get_nombre().isEmpty() 
                            ? viaje.get_conductor().get_nombre() 
                            : "N/A",

                        viaje.get_conductor().get_correo() != null && !viaje.get_conductor().get_correo().isEmpty() 
                            ? viaje.get_conductor().get_correo() 
                            : "N/A",

                        viaje.get_conductor().get_telefono() != null && !viaje.get_conductor().get_telefono().isEmpty() 
                            ? viaje.get_conductor().get_telefono() 
                            : "N/A",

                        viaje.get_conductor().get_placa_vehiculo() != null && !viaje.get_conductor().get_placa_vehiculo().isEmpty()
                            ? viaje.get_conductor().get_placa_vehiculo()
                            : "N/A",

                        viaje.get_conductor().get_modelo_vehiculo() != null && !viaje.get_conductor().get_modelo_vehiculo().isEmpty()
                            ? viaje.get_conductor().get_modelo_vehiculo()
                            : "N/A"
                    });
                }
            }
        }

        // Verificar si se encontraron viajes
        if (modeloViaje.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, 
                "No se encontraron viajes en el rango de fechas seleccionado.", 
                "Sin Resultados", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    
        dispose();
    }//GEN-LAST:event_buscar_porfechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasajeroHistorialFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasajeroHistorialFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasajeroHistorialFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasajeroHistorialFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> año_desde;
    private javax.swing.JComboBox<String> año_hasta;
    private javax.swing.JButton buscar_porfecha;
    private javax.swing.JComboBox<String> dia_desde;
    private javax.swing.JComboBox<String> dia_hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> mes_desde;
    private javax.swing.JComboBox<String> mes_hasta;
    // End of variables declaration//GEN-END:variables
}
