
package Vista;

import Models.Conductor;
import Models.Ruta;
import Models.Viaje;
import Repository.ConductorRepository;
import Repository.RutaRepository;
import Repository.ViajeRepository;
import Views2.ConductorPerfil;
import Views2.Destinos;
import Views2.IniciarSesionPrincipal;
import Views2.Inicio;
import Views2.Nosotros;
import Views2.ViajeAsignado;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Random;
import javax.swing.JPanel;
import java.sql.Statement;


/**
 *
 * @author USER
 */
public class DashboardConductor extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private Conductor conductor;
    private Statement st;

    public DashboardConductor(Conductor conductor, Statement st) {
        this.st = st;
        this.conductor = conductor;
        comprobar_viaje();
        initComponents();
        setDate();
        initContent();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    private void setDate(){
        LocalDate now= LocalDate.now();
        Locale spanishLocale = new Locale ( "es", "ES");
        fecha.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }
    
    private void initContent(){
        ShowJPanel(new ConductorPerfil(conductor, st));
    }
    public void ShowJPanel(JPanel in){
        in.setSize(1010, 580);
        in.setLocation(0, 0);
        content.removeAll();
        content.add(in, BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }
    private void comprobar_viaje(){
        ConductorRepository cr = new ConductorRepository(st);
        List<Conductor> conductores_libres = cr.listar_libres();
        if(conductores_libres == null){
            return;
        }
        
        for(Conductor conductor_libre:conductores_libres){
            if(conductor_libre.get_dni().equals(conductor.get_dni())){
                List<Viaje> viajes_activos = new ViajeRepository(st).listar_activos();
                
                Ruta ruta_elegida = null;
                List<Ruta> rutas = new RutaRepository(st).listar();
                if(rutas == null){
                    return;
                }
                if(viajes_activos != null){
                    
                    
                    int menor_repeticion = -1;
                    for(Ruta ruta:rutas){
                        int aux=0;
                        for(Viaje viaje:viajes_activos){
                            if(viaje.get_ruta().get_id_ruta().equals(ruta.get_id_ruta())){
                                aux++;
                            }
                        }

                        if(menor_repeticion != -1){
                            if(aux<menor_repeticion){
                                menor_repeticion = aux;
                                ruta_elegida = ruta;
                            }
                            continue;
                        }
                        menor_repeticion = aux;
                        ruta_elegida = ruta;
                    }
                } else {
                    ruta_elegida = rutas.get(new Random().nextInt(rutas.size()));
                }
                
                String id_viaje;
                Random random = new Random();
                do{
                    int codigo = 10000 + random.nextInt(90000);
                    id_viaje = String.valueOf(codigo);
                } while(new ViajeRepository(st).buscar(id_viaje)!=null);
                
                LocalDate fecha_salida = LocalDate.now().plusDays(1);
                LocalTime hora_salida = LocalTime.of(8 + new Random().nextInt(9), 0);
                
                Viaje nuevo_viaje= new Viaje(id_viaje, fecha_salida, ruta_elegida, conductor, hora_salida, true);
                
                new ViajeRepository(st).crear(nuevo_viaje);
                return;
            }
        }
        
        
    }
    
    
    /*private void ShowJPanel(JPanel n){
        n.setSize(1010, 580);
        n.setLocation(0, 0);
        content.removeAll();
        content.add(n, BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        buttonInicio = new javax.swing.JButton();
        buttonDestinos = new javax.swing.JButton();
        buttonViajeAsignado = new javax.swing.JButton();
        buttonNosotros = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 620));

        menu.setBackground(new java.awt.Color(87, 120, 119));

        buttonInicio.setBackground(new java.awt.Color(0,0,0,0));
        buttonInicio.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        buttonInicio.setForeground(new java.awt.Color(255, 255, 255));
        buttonInicio.setText("PERFIL");
        buttonInicio.setBorder(null);
        buttonInicio.setBorderPainted(false);
        buttonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInicioActionPerformed(evt);
            }
        });

        buttonDestinos.setBackground(new java.awt.Color(0,0,0,0));
        buttonDestinos.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        buttonDestinos.setForeground(new java.awt.Color(255, 255, 255));
        buttonDestinos.setText("DESTINOS");
        buttonDestinos.setBorder(null);
        buttonDestinos.setBorderPainted(false);
        buttonDestinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDestinosActionPerformed(evt);
            }
        });

        buttonViajeAsignado.setBackground(new java.awt.Color(0,0,0,0));
        buttonViajeAsignado.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        buttonViajeAsignado.setForeground(new java.awt.Color(255, 255, 255));
        buttonViajeAsignado.setText("VIAJES ASIGNADOS");
        buttonViajeAsignado.setBorder(null);
        buttonViajeAsignado.setBorderPainted(false);
        buttonViajeAsignado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonViajeAsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViajeAsignadoActionPerformed(evt);
            }
        });

        buttonNosotros.setBackground(new java.awt.Color(0,0,0,0));
        buttonNosotros.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        buttonNosotros.setForeground(new java.awt.Color(255, 255, 255));
        buttonNosotros.setText("NOSOTROS");
        buttonNosotros.setBorder(null);
        buttonNosotros.setBorderPainted(false);
        buttonNosotros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNosotrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonViajeAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonNosotros, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(buttonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonViajeAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonNosotros, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        header.setBackground(new java.awt.Color(255, 255, 255));

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(22, 38, 35));
        fecha.setText("Hoy es {dayname} {day} de {month} del {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(fecha)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EncabexadoColexXpres.jpg"))); // NOI18N

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInicioActionPerformed
        ShowJPanel(new ConductorPerfil(conductor, st));
    }//GEN-LAST:event_buttonInicioActionPerformed

    private void buttonDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDestinosActionPerformed
        ShowJPanel(new Destinos());
    }//GEN-LAST:event_buttonDestinosActionPerformed

    private void buttonViajeAsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViajeAsignadoActionPerformed
        ShowJPanel (new ViajeAsignado(conductor, st));
    }//GEN-LAST:event_buttonViajeAsignadoActionPerformed

    private void buttonNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNosotrosActionPerformed
        ShowJPanel(new Nosotros());
    }//GEN-LAST:event_buttonNosotrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DashboardConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton buttonDestinos;
    private javax.swing.JButton buttonInicio;
    private javax.swing.JButton buttonNosotros;
    private javax.swing.JButton buttonViajeAsignado;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
